name: DockerBuildImage
on:
  workflow_dispatch:
  push:
    branches: ["main"]
jobs:
  call_docker_build_teamplate:
    uses: mniranjanr7/DockerBuildTemplate/.github/workflows/actions.yml@main
    with:
      image-name: mniranjanr7/node
      tag-name: ${{github.sha}}
      docker-build-context: dockerimages
    secrets:
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
